robot_name: sample_robot
ego_noise_sources:
  - name: left_wheel
    type: motor
    frame_id: l_wheel
  - name: right_wheel
    type: motor
    frame_id: r_wheel
  - name: cpu_fan
    type: fan
    frame_id: cfan